//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityHomeNpl.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9DFC85_cityhomeEntities : DbContext
    {
        public DB_9DFC85_cityhomeEntities()
            : base("name=DB_9DFC85_cityhomeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tblcat> Tblcats { get; set; }
        public DbSet<Tblproduct> Tblproducts { get; set; }
        public DbSet<Tbluser> Tblusers { get; set; }
    }
}
