//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityHomeNpl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tblproduct
    {
        public int Productid { get; set; }
        public string Modelname { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Categoryid { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string FrontDisplay { get; set; }
    }
}
